services:
  web:
    image: wedup-backend
    ports:
      - "8090:8090"
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped
  #   depends_on:
  #     - db
  # db:
  #   image: postgres
